# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /salaries-system

# copy csproj and restore as distinct layers
COPY *.sln .
COPY /salaries-system/ *.csproj ./salaries-system/
RUN dotnet restore

# copy everything else and build app
COPY /salaries-system/. ./salaries-system/
WORKDIR /salaries-system/
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /salaries-system ./
ENTRYPOINT ["dotnet", "cicd-1-salaries.dll"]
