# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /cicd-1-salaries/cicd-1-salaries/

# copy csproj and restore as distinct layers
COPY *.sln .
COPY cicd-1-salaries/*.csproj ./cicd-1-salaries/
RUN dotnet restore

# copy everything else and build app
COPY cicd-1-salaries/. ./cicd-1-salaries/
WORKDIR /cicd-1-salaries/cicd-1-salaries/
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "aspnetapp.dll"]